### ISSUE TITLE
npm run start not working

### ISSUE THREAD

**Issue by SamuelBisberg** [jherr/trpc-intro#1]
Hello, 
I'm using "npm run start" at the route of the apps and it's not working...
I get the following error: 
-----------------------------
> packages@1.0.0 start
> concurrently "wsrun --parallel start"

'concurrently' is not recognized as an internal or external command,
operable program or batch file.
-----------------------------

I copied the package.json content and installed all other dependencies.
What can I do to fix it?

**Comment by jherr** [comment]
Try `npm install concurrently -D`
